# Generated by Django 5.2.8 on 2025-11-26 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='datasets/')),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('doi', models.CharField(editable=False, max_length=100, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
